function getRestrictionNamesMapping() {
    return restrictionMapping
}

var restrictionMapping = {
    'AdaptationOfWorkplace': 'Adaptation Of Workplace',
    'BanOnAllEvents': 'Banning of On All Events',
    'ClosDaycare': 'Closure of Day Care',
    'ClosDaycarePartial': 'Clos Daycare Partial',
    'ClosHigh': 'Closure of Highschools',
    'ClosHighPartial': 'Closure of Highschool Partial',
    'ClosPrim': 'Closure of Primary Schools',
    'ClosPrimPartial': 'Closure of Prim Partial',
    'ClosPubAny': 'Closure of Pub Any',
    'ClosPubAnyPartial': 'Clos Pub Any Partial',
    'ClosSec': 'Clos Sec',
    'ClosSecPartial': 'Clos Sec Partial',
    'EntertainmentVenues': 'Entertainment Venues',
    'EntertainmentVenuesPartial': 'Entertainment Venues Partial',
    'GymsSportsCentres': 'Gyms Sports Centres',
    'GymsSportsCentresPartial': 'Gyms Sports Centres Partial',
    'HotelsOtherAccommodation': 'Hotels Other Accommodation',
    'HotelsOtherAccommodationPartial': 'Hotels Other Accommodation Partial',
    'IndoorOver100': 'Restriction Of Indoor Events Over 100',
    'IndoorOver1000': 'Restriction Of Indoor Events Over 1000',
    'MasksMandatoryAllSpaces': 'MasksMandatory All Spaces',
    'MasksMandatoryClosedSpaces': 'MasksMandatory ClosedS paces',
    'Masks MandatoryClosedSpaces Partial': 'Masks Mandatory Closed Spaces Partial',
    'MasksVoluntaryClosedSpacesPartial': 'Masks Voluntary Closed Spaces Partial',
    'MassGather50': 'Mass Gather 50',
    'MassGatherAll': 'Mass Gather All',
    'NonEssentialShops': 'Non Essential Shops',
    'NonEssentialShopsPartial': 'NonEssential Shops Partial',
    'OutdoorOver1000': 'Restriction Of Outoor Events  Over 1000',
    'OutdoorOver50': 'Restriction Of Outoor Events  Over 50',
    'OutdoorOver500': 'Restriction Of Outoor Events  Over 500',
    'PlaceOfWorship': 'Place Of Worship',
    'PlaceOfWorshipPartial': 'Place Of Worship Partial',
    'PrivateGatheringRestrictions': 'Private Gathering Restrictions',
    'PrivateGatheringRestrictionsPartial': 'Private Gathering Restrictions Partial',
    'QuarantineForInternationalTravellers': 'Quarantine For International Travellers',
    'RegionalStayHomeOrder': 'Regional Stay Home Order',
    'RestaurantsCafes': 'Restaurants Cafes',
    'RestaurantsCafesPartial': 'Restaurants Cafes Partial',
    'SocialCircle': 'Social Circle',
    'StayHomeGen': 'Stay Home Gen',
    'StayHomeOrder': 'Stay Home Order',
    'StayHomeOrderPartial': 'Stay Home Order Partial',
    'Teleworking': 'Teleworking',
    'BanOnAllEventsPartial': 'Banning of On All Events Partial',
    'IndoorOver500': 'Restriction Of Indoor Events Over 500',
    'MasksMandatoryAllSpacesPartial': 'Masks Mandatory All Spaces Partial',
    'MasksVoluntaryAllSpaces': 'Masks Voluntary All Spaces',
    'MassGather50Partial': 'Mass Gather 50 Partial',
    'MassGatherAllPartial': 'Mass Gather All Partial',
    'StayHomeGenPartial': 'Stay Home Gen Partial',
    'TeleworkingPartial': 'Teleworking Partial',
    'QuarantineForInternationalTravellersPartial': 'Quarantine For International Travellers Partial',
    'AdaptationOfWorkplacePartial': 'Adaptation Of Workplace Partial',
    'ClosureOfPublicTransport': 'Closure Of Public Transport',
    'ClosureOfPublicTransportPartial': 'Closure Of Public Transport Partial',
    'IndoorOver50': 'Restriction Of Indoor Events Over 50',
    'StayHomeRiskG': 'Stay Home Risk G',
    'OutdoorOver100': 'Restriction Of Outoor Events Over 100',
    'WorkplaceClosures': 'Workplace Closures',
    'WorkplaceClosuresPartial': 'Workplace Closures Partial',
    'MasksVoluntaryAllSpacesPartial': 'Masks Voluntary All Spaces Partial',
    'MasksVoluntaryClosedSpaces': 'Masks Voluntary Closed Spaces',
    'StayHomeRiskGPartial': 'Stay HomeRisk G Partial',
    'RegionalStayHomeOrderPartial': 'Regional Stay Home Order Partial',
    'SocialCirclePartial': 'Social Circle Partial'
}